# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.


In [1]:
# Exercise 1
import numpy as np

array = np.arange(1, 11)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]



---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.


In [2]:
# Exercise 2
import numpy as np

zero_array = np.zeros((3, 3))
print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.


In [3]:
# Exercise 3
import numpy as np

array = np.linspace(0, 5, 10)
print(array)


[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]



---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.


In [4]:
# Exercise 4
import numpy as np

identity_matrix = np.eye(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]



---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.


In [5]:
# Exercise 5
import numpy as np

random_matrix = np.random.rand(4, 4)
print(random_matrix)

[[2.77020710e-01 2.56477409e-01 3.86020480e-01 3.61231867e-01]
 [1.28232504e-04 8.26081115e-01 3.65483931e-02 2.87041366e-01]
 [6.27417212e-01 7.22468734e-01 8.08817946e-01 1.59288322e-01]
 [3.77846968e-03 7.99848009e-01 9.50562633e-01 4.64878857e-01]]



---

### Exercise 6:
Find the shape of a NumPy array.


In [8]:
# Exercise 6
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.shape)

(2, 3)



---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.


In [11]:
# Exercise 7
import numpy as np
array_1d = np.arange(16)
array_4x4 = array_1d.reshape(4, 4)

print(array_4x4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



---

### Exercise 8:
Find the data type of the elements in a NumPy array.


In [12]:
# Exercise 8
import numpy as np

array = np.array([1, 2, 3, 4])
print(array.dtype)

int32



---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.


In [13]:
# Exercise 9
import numpy as np
arr = np.arange(1, 101)
even_numbers = arr[arr % 2 == 0]

print(even_numbers)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]



---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.


In [14]:
# Exercise 10
import numpy as np

random_matrix = np.random.randint(10, 51, size=(6, 6))
print(random_matrix)

[[48 32 13 26 35 15]
 [22 44 40 22 11 46]
 [50 42 21 36 46 34]
 [29 12 34 44 29 21]
 [49 15 17 34 29 31]
 [32 13 49 49 27 34]]



---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.


In [101]:
# Exercise 11
import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
submatrix = arr[0:2, 1:3]
print("Original Array:")
print(arr)

print("\nSubmatrix:")
print(submatrix)

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Submatrix:
[[2 3]
 [5 6]]



---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.


In [102]:
# Exercise 12
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
total_sum = arr.sum()
print(total_sum)

21



---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.


In [103]:
# Exercise 13
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
mean_val = np.mean(arr)
median_val = np.median(arr)
std_dev = np.std(arr)
print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_dev)

Mean: 5.0
Median: 5.0
Standard Deviation: 2.581988897471611



---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.


In [106]:
# Exercise 14
import numpy as np

arr = np.array([4, 7, 1, 9, 3, 8])
max = np.max(arr)
min= np.min(arr)
print("Maximum value:", max_value)
print("Minimum value:", min_value)

Maximum value: 9
Minimum value: 1



---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.


In [107]:
# Exercise 15
import numpy as np

arr = np.random.randint(0, 100, size=20)
print("Array:", arr)
max_index = np.argmax(arr)
print("Index of the maximum value:", max_index)

Array: [75 37 53 11 41 87 98 26 53 83 74 10 76  2 22 85 99 26 31  2]
Index of the maximum value: 16



---

### Exercise 16:
Create a NumPy array and reverse its elements.


In [108]:
# Exercise 16
import numpy as np
arr16 = np.arange(10)[::-1]
arr16

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])


---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [109]:
# Exercise 17
import numpy as np
mat1 = np.random.randint(1, 10, (3, 3))
mat2 = np.random.randint(1, 10, (3, 3))
elementwise_product17 = mat1 * mat2
elementwise_product17

array([[ 9,  6,  6],
       [40, 14,  8],
       [ 8, 72, 12]])


---

### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [110]:
# Exercise 18
import numpy as np
array = np.array([10, 20, 30, 40])
diagonal_matrix = np.diag(array)
print("Diagonal matrix:\n", diagonal_matrix)

Diagonal matrix:
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]



---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [115]:
# Exercise 19
import numpy as np

A = np.array([[1, 2],[3, 4]])
              
B = np.array([[5, 6],[7, 8]])
              
result = np.dot(A, B)

print("Matrix multiplication result (A * B):")
print(result)



Matrix multiplication result (A * B):
[[19 22]
 [43 50]]



---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.


In [116]:
# Exercise 20
import numpy as np

array_2d = np.array([[10, 20, 30],[40, 50, 60]])
                     
flattened_array = array_2d.flatten()
print("Flattened 1D array:", flattened_array)

Flattened 1D array: [10 20 30 40 50 60]



---

### Exercise 21:
Stack two NumPy arrays vertically.


In [117]:
# Exercise 21
a21 = np.array([[1, 2], [3, 4]])
b21 = np.array([[5, 6]])
stacked_v21 = np.vstack((a21, b21))
stacked_v21

array([[1, 2],
       [3, 4],
       [5, 6]])


---

### Exercise 22:
Stack two NumPy arrays horizontally.


In [118]:
# Exercise 22
import numpy as np
stacked_h22 = np.hstack((a21, b21.T))
stacked_h22

array([[1, 2, 5],
       [3, 4, 6]])


---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.


In [119]:
# Exercise 23
import numpy as np
arr23 = np.arange(12)
split23 = np.split(arr23, 4)
split23

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]


---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.


In [120]:
# Exercise 24
import numpy as np
arr24 = np.random.rand(5, 5)
rounded24 = np.round(arr24, 2)
rounded24


array([[0.64, 0.96, 0.38, 0.77, 0.08],
       [0.82, 0.76, 0.61, 0.38, 0.27],
       [0.96, 0.99, 0.84, 0.64, 0.11],
       [0.87, 0.09, 0.7 , 0.49, 0.59],
       [0.23, 0.94, 0.76, 0.06, 0.79]])


---

### Exercise 25:
Find the unique elements of a NumPy array.


In [29]:
# Exercise 25
import numpy as np
arr = np.array([1, 2, 2, 3, 4, 4, 5])
unique_vals = np.unique(arr)
print(unique_vals)

[1 2 3 4 5]



---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.


In [121]:
# Exercise 26
import numpy as np
arr = np.array([5, 2, 8, 1])

print(arr)

[5 2 8 1]



---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.


In [122]:
# Exercise 27
import numpy as np
arr27 = np.array([1, 2, 3])
cumsum27 = np.cumsum(arr27)
cumsum27

array([1, 3, 6])


---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.


In [123]:
# Exercise 28
import numpy as np
arr28 = np.array([0, 1, 0, 2, 3])
nonzero28 = np.count_nonzero(arr28)
nonzero28

3


---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.


In [124]:
# Exercise 29
import numpy as np
arr29 = np.random.randint(0, 100, 10)
sorted29 = np.sort(arr29)
sorted29

array([ 0, 12, 26, 43, 53, 69, 69, 71, 72, 91])


---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.


In [125]:
# Exercise 30
import numpy as np
mat30 = np.random.randint(1, 10, (3, 3))
row_sum30 = mat30.sum(axis=1)
col_sum30 = mat30.sum(axis=0)
print(row_sum30, col_sum30)

[16 25  9] [18 19 13]



---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).


In [93]:
# Exercise 31
import numpy as np
arr31 = np.random.rand(3, 3)
norm31 = (arr31 - arr31.min()) / (arr31.max() - arr31.min())
norm31

array([[0.48674093, 0.        , 0.29621578],
       [0.31361003, 1.        , 0.35751138],
       [0.28143553, 0.70275574, 0.09313584]])


---

### Exercise 32:
Create two NumPy arrays and find the dot product.


In [92]:
# Exercise 32
import numpy as np
a32 = np.array([1, 2])
b32 = np.array([3, 4])
dot32 = np.dot(a32, b32)
dot32

11


---

### Exercise 33:
Find the trace of a square NumPy matrix.


In [91]:
# Exercise 33
import numpy as np
mat33 = np.array([[1, 2], [3, 4]])
trace33 = np.trace(mat33)
trace33

5


---

### Exercise 34:
Create a 2D array and swap two rows.


In [90]:
# Exercise 34
import numpy as np
mat34 = np.array([[1, 2], [3, 4]])
mat34[[0, 1]] = mat34[[1, 0]]
mat34

array([[3, 4],
       [1, 2]])


---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.


In [89]:
# Exercise 35
import numpy as np
arr35 = np.array([1, 2, 3])
col_vec35 = arr35[:, np.newaxis]
col_vec35

array([[1],
       [2],
       [3]])


---

### Exercise 36:
Find the determinant of a 3x3 matrix.


In [88]:
# Exercise 36
import numpy as np
mat36 = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
det36 = np.linalg.det(mat36)
det36

0.9999999999999987


---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.


In [87]:
# Exercise 37
import numpy as np
mat37 = np.array([[4, -2], [1, 1]])
eigvals37, eigvecs37 = np.linalg.eig(mat37)
print(eigvals37, eigvecs37)

[3. 2.] [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]



---

### Exercise 38:
Solve a system of linear equations using NumPy.


In [86]:
# Exercise 38
import numpy as np
#Solve: 4x + 2y = 8, 2x + 4y = 10
A38 = np.array([[4, 2], [2, 4]])
b38 = np.array([8, 10])
solution38 = np.linalg.solve(A38, b38)
solution38

array([1., 2.])


---

### Exercise 39:
Add Gaussian noise to a NumPy array.


In [85]:
# Exercise 39
import numpy as np
arr39 = np.array([1, 2, 3])
noise39 = np.random.normal(0, 1, arr39.shape)
noisy_arr39 = arr39 + noise39
noisy_arr39

array([0.50634528, 1.76671694, 3.91100276])


---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.


In [82]:
# Exercise 40
import numpy as np
mat40 = np.random.randint(1, 10, (4, 4))
diag40 = np.diag(mat40)
diag40

array([8, 9, 6, 5])


---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.


In [126]:
# Exercise 41
import numpy as np
arr21 = np.random.rand(100) * 100
clipped21 = np.clip(arr21, 20, 40)
clipped21

array([40.        , 40.        , 40.        , 26.87111654, 36.78246497,
       40.        , 36.21384861, 40.        , 28.59622715, 30.26478793,
       38.00727261, 40.        , 20.        , 37.39093255, 40.        ,
       24.6379144 , 40.        , 40.        , 40.        , 28.86712125,
       30.88339312, 40.        , 40.        , 40.        , 40.        ,
       40.        , 34.2390911 , 20.        , 20.        , 20.        ,
       40.        , 40.        , 40.        , 40.        , 20.        ,
       22.83826256, 36.84158792, 40.        , 40.        , 40.        ,
       20.        , 40.        , 40.        , 29.72847748, 40.        ,
       20.        , 40.        , 40.        , 40.        , 40.        ,
       40.        , 40.        , 40.        , 27.73069778, 20.        ,
       20.        , 28.7471793 , 35.35490857, 37.2180406 , 40.        ,
       40.        , 40.        , 36.50359598, 20.        , 20.        ,
       40.        , 22.40827335, 20.        , 40.        , 35.97


---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.


In [80]:
# Exercise 42
import numpy as np
arr42 = np.array([[1, -1], [-5, 4]])
arr42[arr42 < 0] = 0
arr42

array([[1, 0],
       [0, 4]])


---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.


In [79]:
# Exercise 43
import numpy as np
a43 = np.array([1, 2])
b43 = np.array([3, 4])
inner43 = np.inner(a43, b43)
outer43 = np.outer(a43, b43)
print(outer43, inner43)

[[3 4]
 [6 8]] 11



---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.


In [77]:
# Exercise 
import numpy as np
points44 = np.random.rand(4, 2)
from scipy.spatial.distance import pdist, squareform
distances44 = squareform(pdist(points44))
distances44

array([[0.        , 0.1546658 , 0.22783854, 0.71292599],
       [0.1546658 , 0.        , 0.14975514, 0.6869489 ],
       [0.22783854, 0.14975514, 0.        , 0.53755889],
       [0.71292599, 0.6869489 , 0.53755889, 0.        ]])


---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.


In [75]:
# Exercise 45
import numpy as np
arr45 = np.array([('Alice', 25, 5.5), ('Bob', 30, 6.0)],
                 dtype=[('name', 'U10'), ('age', 'i4'), ('height', 'f4')])
arr45

array([('Alice', 25, 5.5), ('Bob', 30, 6. )],
      dtype=[('name', '<U10'), ('age', '<i4'), ('height', '<f4')])


---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.


In [73]:
# Exercise 46
import numpy as np
mat46 = np.random.randint(0, 5, (5, 5))
unique_vals46, counts46 = np.unique(mat46, return_counts=True)
counts46

array([3, 4, 6, 3, 9], dtype=int64)


---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.


In [72]:
# Exercise 47
import numpy as np
mat47 = np.random.rand(3, 3)
mean_row47 = mat47.mean(axis=1, keepdims=True)
centered47 = mat47 - mean_row47
centered47

array([[ 0.30714245, -0.00835859, -0.29878386],
       [-0.22458623,  0.20303001,  0.02155622],
       [ 0.13435644, -0.18906676,  0.05471032]])


---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.


In [71]:
# Exercise 48
import numpy as np
arr48 = np.random.randint(0, 100, 10)
any_gt_50 = np.any(arr48 > 50)
any_gt_50

True


---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.


In [70]:
# Exercise 49
import numpy as np
arr49 = np.random.rand(10)
window = 3
moving_avg49 = np.convolve(arr49, np.ones(window)/window, mode='valid')
moving_avg49

array([0.59260851, 0.53609868, 0.55739752, 0.47889952, 0.51130328,
       0.50146089, 0.31325785, 0.24837662])


---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.


In [69]:
# Exercise 50
import numpy as np

x = np.array([10, 20, 30])
y = np.array([15, 25, 35])
r = np.corrcoef(x, y)[0, 1]
print("Correlation:", r)

Correlation: 1.0



---

### Exercise 51:
Convert a NumPy array of radians to degrees.


In [66]:
# Exercise 51
import numpy as np
rad51 = np.array([0, np.pi/2, np.pi])
deg51 = np.degrees(rad51)
deg51

array([  0.,  90., 180.])


---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.


In [61]:
# Exercise 52
import numpy as np
arr42 = np.random.rand(20)
var42 = np.var(arr42)
std42 = np.std(arr42)
print(var42, std42)

0.08296221105156662 0.2880316146737483



---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.


In [65]:
# Exercise 53
import numpy as np
arr53 = np.random.rand(3, 3)
max_idx_row53 = np.argmax(arr53, axis=1)
max_idx_col53 = np.argmax(arr, axis=0)
print(max_idx_row53, max_idx_col53)

[1 2 2] [2 2 2]



---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.


In [58]:
# Exercise 54
import numpy as np
mat54 = np.array([[4, 7], [2, 6]])
inv54 = np.linalg.inv(mat54)
inv54

array([[ 0.6, -0.7],
       [-0.2,  0.4]])


---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).


In [57]:
# Exercise 55
import numpy as np
arr55 = np.random.rand(10)
standardized55 = (arr55 - np.mean(arr55)) / np.std(arr55)
standardized55

array([-0.95684037, -2.32434382,  0.2832998 ,  0.19430159,  0.22688579,
        0.57770081,  1.13360729, -0.74047863,  0.63578765,  0.97007989])


---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.


In [56]:
# Exercise 56
import numpy as np
a56 = np.array([1, 2, 3])
b56 = np.array([4, 5, 6])
add56 = a56 + b56
sub56 = a56 - b56
print(add56, sub56)

[5 7 9] [-3 -3 -3]



---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.


In [55]:
# Exercise 57
import numpy as np
arr57 = np.random.rand(10)
max_index57 = np.argmax(arr57)
max_index57

2


---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.


In [50]:
# Exercise 58
import numpy as np
arr58 = np.arange(9).reshape(3, 3)
rotated58 = np.rot90(arr58)
rotated58


array([[2, 5, 8],
       [1, 4, 7],
       [0, 3, 6]])


---

### Exercise 59:
Compute the Frobenius norm of a matrix.


In [48]:
# Exercise 59
import numpy as np
mat59 = np.array([[1, 2], [3, 4]])
frobenius59 = np.linalg.norm(mat59)
frobenius59

5.477225575051661


---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.


In [49]:
# Exercise 60
import numpy as np
arr60 = np.arange(27).reshape(3, 3, 3)
subarr60 = arr60[1:, :, 1:]
subarr60

array([[[10, 11],
        [13, 14],
        [16, 17]],

       [[19, 20],
        [22, 23],
        [25, 26]]])


---